version: '3.4'

services: 
  handmade_shop_porstgresql:
    image: postgres:15-alpine
    
  handmade_shop_rabbitmq:
    image: rabbitmq:management
    
  handmade_shop_redis:
    image: redis
      
  handmade_shop_identity:
    image: ${DOCKER_REGISTRY-}handmade_shop_identity
    build:
      context: .
      dockerfile: src/Presentation/Identity/HandmadeShop.Identity/Dockerfile
    depends_on:
      - handmade_shop_api
  
  handmade_shop_worker:
    image: ${DOCKER_REGISTRY-}handmade_shop_worker
    build:
      context: .
      dockerfile: src/Presentation/Worker/HandmadeShop.Worker/Dockerfile
    depends_on:
      - handmade_shop_api
  
  handmade_shop_api:
    image: ${DOCKER_REGISTRY-}handmade_shop_api
    build:
      context: .
      dockerfile: src/Presentation/Api/HandmadeShop.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - handmade_shop_porstgresql
      - handmade_shop_rabbitmq
      - handmade_shop_redis
  
  handmade_shop_web:
    image: ${DOCKER_REGISTRY-}handmade_shop_web
    build:
      context: .
      dockerfile: src/Presentation/Web/HandmadeShop.Web/Dockerfile
    depends_on:
      - handmade_shop_api
      - handmade_shop_porstgresql
  
  